#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

runApplication blockMesh
cp 0/T.orig 0/T
runApplication foamPostProcess -func generateT -time 0
for case in CN*; do
    rm -r $case/0.* $case/1.*
    $application -case $case |& tee $case/log
done

#------------------------------------------------------------------------------
