#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

runApplication blockMesh
cp 0/T.orig 0/T
runApplication foamPostProcess -func generateT -time 0
rm -rf 0.* 1.*
$application | tee log

# Calculate errors at the final time
errorNorms . 0 T 1 T
#------------------------------------------------------------------------------
