#!/bin/bash -e
rm -rf [0-9]*  constant/polyMesh

# Mesh generation
blockMesh

# Initialization
rm -rf 0; cp -r init0 0

# Run
foamRun >& log & sleep 0.01;tail -f log

# Plot graphs
function plotProfile {
    if [ "$#" -ne 2 ]; then
        echo usage: plotProfile time field
        return 1
    fi
    time=$1
    f=$2
    export time
    writeCellDataxyz -time $time $f
    sed '1d' $time/$f.xyz | sort -k3,3n | sponge $time/$f.xyz
    gmtPlot plots/plot${f}.gmt
}

function plotProfiles {
    if [ "$#" -ne 1 ]; then
        echo usage: plotProfiles time
        return 1
    fi
    time=$1
    for f in U T nut alphat k epsilon; do
        plotProfile $time $f
    done
    sed 's/TIME/'$time'/g' plots/plotAll.lyx > $time/plotAll.lyx
    lyx --export pdf $time/plotAll.lyx

}

plotProfiles 0
cp 0/plotAll.pdf .
evince plotAll.pdf &
for time in [1-9]?? [1-9]??? ; do
    plotProfiles $time
    echo $time
    pdfunite plotAll.pdf $time/plotAll.pdf plotAll2.pdf
    mv plotAll2.pdf plotAll.pdf
done

