#!/bin/bash -e

if [ "$#" -ne 1 ]; then
    echo usage: runOne case
    exit
fi

case=$1
if [ ! -d $case ]; then
    echo $case does not exist
    exit
fi

rm -rf $case/[1-9]*  $case/uStar.* $case/log $case/gmt.*

# Mesh generation
#blockMesh -case $case

# Initialization
#rm -rf $case/0; cp -r init0 $case/0

# Run
foamRun -case $case | tee $case/log 

# Post processing
./plots/plots.sh $case

#To do:
# include theta
# More diagnostics - terms of Sk, length scale
# Recalc ustar using logs to reduce u*?

# Comarisons between cases
for var in T U; do
    $SCRIPT_DIR/plotCompare.sh $var
done
